const KEY='condoMaintenanceManager.v1';
const seed={units:[],violations:[],work:[],pool:[],tasks:[],rules:[],golden:[],events:[],notes:[]};
let db=JSON.parse(localStorage.getItem(KEY)||'null')||seed; Object.keys(seed).forEach(k=>db[k]??=[]);
const tabs=['Hub','Owners & Units','Violations','Work Log','Pool Tests','Calendar','Golden List','Rules Library','Monthly Report','Settings'];
const $=id=>document.getElementById(id); const save=()=>localStorage.setItem(KEY,JSON.stringify(db));
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7); const today=()=>new Date().toISOString().slice(0,10);
function init(){ $('tabs').innerHTML=tabs.map((t,i)=>`<button class="tab ${i?'':'active'}" onclick="show('${t}',this)">${t}</button>`).join(''); show('Hub',document.querySelector('.tab')); }
function show(tab,btn){ document.querySelectorAll('.tab').forEach(b=>b.classList.remove('active')); btn?.classList.add('active'); $('content').innerHTML=views[tab](); }
function unitByNo(n){return db.units.find(u=>u.unit===String(n).trim())}
function ensureUnit(n){ if(!n) return null; let u=unitByNo(n); if(!u){u={id:uid(),unit:String(n).trim(),owner:'',phone:'',email:'',notes:''};db.units.push(u);save()} return u; }
function grammar(id){let el=$(id); const fixes=[[ /\bi\b/g,'I'],[/\bteh\b/gi,'the'],[/\brecieve\b/gi,'receive'],[/\bgrammer\b/gi,'grammar'],[/\bviolaton\b/gi,'violation'],[/\bmaintenence\b/gi,'maintenance'],[/\bocurred\b/gi,'occurred'],[/\s+/g,' ']]; let text=el.value; fixes.forEach(([r,v])=>text=text.replace(r,v)); text=text.replace(/(^|[.!?]\s+)([a-z])/g,(m,p,c)=>p+c.toUpperCase()); el.value=text.trim(); }
function del(col,id){ if(confirm('Delete this item permanently?')){db[col]=db[col].filter(x=>x.id!==id);save();init()} }
function ownerForm(u={}){return `<div class="row"><label>Unit #<input id="unit" value="${u.unit||''}"></label><label>Owner Name<input id="owner" value="${u.owner||''}"></label><label>Phone<input id="phone" value="${u.phone||''}"></label><label>Email<input id="email" value="${u.email||''}"></label></div><label>Owner / Unit Notes<textarea id="notes">${u.notes||''}</textarea></label><div class="toolbar"><button onclick="saveUnit('${u.id||''}')">Save Owner File</button><button class="secondary" onclick="grammar('notes')">Fix Spelling / Grammar</button></div>`}
function saveUnit(id){let u=id?db.units.find(x=>x.id===id):ensureUnit($('unit').value); Object.assign(u,{unit:$('unit').value,owner:$('owner').value,phone:$('phone').value,email:$('email').value,notes:$('notes').value}); save(); init();}
function addViolation(){let u=ensureUnit($('vunit').value); db.violations.push({id:uid(),date:$('vdate').value||today(),unit:u.unit,owner:u.owner,rule:$('vrule').value,details:$('vdetails').value,photos:$('vphotos').value,status:$('vstatus').value}); save(); init();}
function addWork(){db.work.push({id:uid(),date:$('wdate').value||today(),unit:$('wunit').value,category:$('wcat').value,performed:$('wperf').value,parts:$('wparts').value,hours:$('whours').value,status:$('wstatus').value}); save(); init();}
function addPool(){db.pool.push({id:uid(),date:$('pdate').value||today(),body:$('pbody').value,chlorine:$('pch').value,ph:$('pph').value,alk:$('palk').value,temp:$('ptemp').value,notes:$('pnotes').value}); save(); init();}
function addTask(){db.tasks.push({id:uid(),date:$('tdate').value||today(),title:$('ttitle').value,type:$('ttype').value,done:false,notes:$('tnotes').value}); save(); init();}
function completeTask(id){let t=db.tasks.find(x=>x.id===id); t.done=!t.done; if(t.done) db.work.push({id:uid(),date:today(),unit:'Common Area',category:'Golden List / Task',performed:`Completed: ${t.title}`,parts:'',hours:'',status:'Complete'}); save(); init();}
function addRule(){db.rules.push({id:uid(),name:$('rname').value,section:$('rsec').value,text:$('rtext').value}); save(); init();}
function addGolden(){db.golden.push({id:uid(),title:$('gtitle').value,frequency:$('gfreq').value,area:$('garea').value,notes:$('gnotes').value}); save(); init();}
function addGoldenToday(id){let g=db.golden.find(x=>x.id===id); if(!g)return; db.tasks.push({id:uid(),date:today(),title:g.title,type:'Golden List',done:false,notes:g.notes}); save(); init();}
const views={
'Hub':()=>`<div class="grid"><div class="card span-3"><div class="metric">${db.units.length}/78</div><b>Owner files</b></div><div class="card span-3"><div class="metric">${db.tasks.filter(t=>!t.done).length}</div><b>Open reminders</b></div><div class="card span-3"><div class="metric">${db.violations.filter(v=>v.status!=='Closed').length}</div><b>Open violations</b></div><div class="card span-3"><div class="metric">${db.work.filter(w=>w.date.slice(0,7)===today().slice(0,7)).length}</div><b>This month's work</b></div><div class="card span-6"><h2>Daily Reminder Hub</h2>${db.tasks.filter(t=>!t.done).map(t=>`<div class="item"><div class="item-head"><b>${t.title}</b><span class="pill">${t.date}</span></div><p>${t.notes||''}</p><button class="ok" onclick="completeTask('${t.id}')">Mark Complete + Log</button></div>`).join('')||'<p class="muted">No open tasks. Add calendar reminders or golden-list maintenance ideas.</p>'}</div><div class="card span-6"><h2>Quick Task / Alarm</h2><label>Date<input id="tdate" type="date" value="${today()}"></label><label>Task<input id="ttitle" placeholder="Inspect lights, check gates, call vendor..."></label><label>Type<select id="ttype"><option>Reminder</option><option>Alarm</option><option>Schedule</option><option>Inspection</option></select></label><label>Notes<textarea id="tnotes"></textarea></label><button onclick="addTask()">Save Reminder</button></div></div>`,
'Owners & Units':()=>`<div class="grid"><div class="card span-12"><h2>Owner Files</h2>${ownerForm()}<div class="list">${db.units.sort((a,b)=>a.unit.localeCompare(b.unit,undefined,{numeric:true})).map(u=>`<div class="item"><div class="item-head"><div><b>Unit ${u.unit}</b> — ${u.owner||'Owner pending'}<br><span class="muted">${u.phone||''} ${u.email||''}</span></div><button class="danger" onclick="del('units','${u.id}')">Delete</button></div>${ownerForm(u)}</div>`).join('')}</div></div></div>`,
'Violations':()=>`<div class="card"><h2>Violation Report Builder</h2><div class="row"><label>Date<input id="vdate" type="date" value="${today()}"></label><label>Unit #<input id="vunit" onblur="let u=unitByNo(this.value);$('vowner').value=u?u.owner:''"></label><label>Owner<input id="vowner" readonly></label><label>Status<select id="vstatus"><option>Open</option><option>Notice Sent</option><option>Corrected</option><option>Closed</option></select></label></div><label>Search / Select Rule<select id="vrule"><option></option>${db.rules.map(r=>`<option>${r.section}: ${r.name} — ${r.text}</option>`)}</select></label><label>Details<textarea id="vdetails"></textarea></label><button class="secondary" onclick="grammar('vdetails')">Fix Spelling / Grammar</button><label>Violation Photo Links / File Names<textarea id="vphotos" placeholder="Paste photo URLs, file names, or notes for imported photos"></textarea></label><div class="toolbar"><button onclick="addViolation()">Save Violation</button><button onclick="printNotice()">Design / Print Notice</button></div></div><div class="list">${db.violations.map(v=>`<div class="item"><div class="item-head"><b>${v.date} Unit ${v.unit}: ${v.rule}</b><span class="pill red">${v.status}</span></div><p>${v.details}</p><p class="muted">Photos: ${v.photos||'None listed'}</p><button class="danger" onclick="del('violations','${v.id}')">Delete</button></div>`).join('')}</div>`,
'Work Log':()=>`<div class="card"><h2>Work Performed</h2><div class="row"><label>Date<input id="wdate" type="date" value="${today()}"></label><label>Unit / Area<input id="wunit"></label><label>Category<input id="wcat" placeholder="Plumbing, grounds, electrical..."></label><label>Status<select id="wstatus"><option>Complete</option><option>Open</option><option>Waiting Parts</option><option>Vendor Needed</option></select></label></div><label>Work Performed<textarea id="wperf"></textarea></label><button class="secondary" onclick="grammar('wperf')">Fix Spelling / Grammar</button><div class="row"><label>Parts / Cost<input id="wparts"></label><label>Hours<input id="whours"></label></div><button onclick="addWork()">Log Work</button></div><div class="list">${db.work.map(w=>`<div class="item"><b>${w.date} ${w.unit} - ${w.category}</b><p>${w.performed}</p><span class="pill green">${w.status}</span> <button class="danger" onclick="del('work','${w.id}')">Delete</button></div>`).join('')}</div>`,
'Pool Tests':()=>`<div class="card"><h2>Spa / Pool / Spool Test Sheet</h2><div class="row"><label>Date<input id="pdate" type="date" value="${today()}"></label><label>Body<select id="pbody"><option>Spa</option><option>Pool</option><option>Spool</option></select></label><label>Chlorine<input id="pch"></label><label>pH<input id="pph"></label><label>Alkalinity<input id="palk"></label><label>Temp<input id="ptemp"></label></div><label>Notes<textarea id="pnotes"></textarea></label><button onclick="addPool()">Save Pool Test</button><button class="secondary" onclick="window.print()">Print Monthly Sheet</button></div><div class="list">${db.pool.map(p=>`<div class="item"><b>${p.date} ${p.body}</b> Chlorine ${p.chlorine}, pH ${p.ph}, Alk ${p.alk}, Temp ${p.temp}<p>${p.notes||''}</p><button class="danger" onclick="del('pool','${p.id}')">Delete</button></div>`).join('')}</div>`,
'Calendar':()=>`<div class="card"><h2>Calendar</h2><p class="muted">Checked-off golden-list tasks are added to the work log and monthly report.</p><div class="calendar">${Array.from({length:31},(_,i)=>{let d=today().slice(0,8)+String(i+1).padStart(2,'0');let items=db.tasks.filter(t=>t.date===d);return `<div class="day"><b>${i+1}</b>${items.map(t=>`<div class="tiny">${t.done?'✓':'•'} ${t.title}</div>`).join('')}</div>`}).join('')}</div></div>`,
'Golden List':()=>`<div class="card"><h2>Golden List Maintenance Items</h2><div class="row"><label>Item<input id="gtitle"></label><label>Frequency<input id="gfreq" placeholder="Daily, weekly, monthly"></label><label>Area<input id="garea"></label></div><label>Notes<textarea id="gnotes"></textarea></label><button onclick="addGolden()">Add Golden Item</button></div><div class="list">${db.golden.map(g=>`<div class="item"><b>${g.title}</b> <span class="pill gold">${g.frequency}</span><p>${g.area} ${g.notes}</p><button onclick="addGoldenToday('${g.id}')">Add to Today</button><button class="danger" onclick="del('golden','${g.id}')">Delete</button></div>`).join('')}</div>`,
'Rules Library':()=>`<div class="card"><h2>Searchable Rules Library</h2><div class="row"><label>Rule Name<input id="rname"></label><label>Section<input id="rsec"></label></div><label>Individual Rule Text<textarea id="rtext"></textarea></label><button class="secondary" onclick="grammar('rtext')">Fix Spelling / Grammar</button><button onclick="addRule()">Add Rule</button></div><div class="list">${db.rules.map(r=>`<div class="item"><b>${r.section}: ${r.name}</b><p>${r.text}</p><button class="danger" onclick="del('rules','${r.id}')">Delete</button></div>`).join('')}</div>`,
'Monthly Report':()=>{let m=today().slice(0,7);return `<div class="card no-card-print"><h2>Monthly Report (${m})</h2><div class="toolbar no-print"><button onclick="window.print()">Print Report</button><a class="btn" href="mailto:?subject=Monthly Maintenance Report ${m}&body=${encodeURIComponent(reportText(m))}">Email Report</a></div><pre style="white-space:pre-wrap">${reportText(m)}</pre></div>`},
'Settings':()=>`<div class="card"><h2>Settings & Data</h2><p>This app stores data in this browser with localStorage. Use Export Backup regularly.</p><button onclick="exportData()">Export JSON Backup</button><button class="danger" onclick="if(confirm('Clear all data?')){db=JSON.parse(JSON.stringify(seed));save();init()} ">Clear All Data</button></div>`
};
function reportText(m){return [`MONTHLY MAINTENANCE REPORT ${m}`,'','WORK LOG',...db.work.filter(w=>w.date.startsWith(m)).map(w=>`- ${w.date} ${w.unit} ${w.category}: ${w.performed} (${w.status})`),'','VIOLATIONS',...db.violations.filter(v=>v.date.startsWith(m)).map(v=>`- ${v.date} Unit ${v.unit}: ${v.rule} ${v.status}`),'','POOL TESTS',...db.pool.filter(p=>p.date.startsWith(m)).map(p=>`- ${p.date} ${p.body}: chlorine ${p.chlorine}, pH ${p.ph}, alk ${p.alk}, temp ${p.temp}`)].join('\n')}
function printNotice(){let unit=$('vunit').value, u=ensureUnit(unit); let html=`<div class="notice"><h1>Violation Notice</h1><p><b>Date:</b> ${$('vdate').value||today()}</p><p><b>Unit:</b> ${unit}</p><p><b>Owner:</b> ${u.owner||'Owner pending'}</p><p><b>Rule:</b> ${$('vrule').value}</p><p><b>Details:</b> ${$('vdetails').value}</p><p>Please correct this violation promptly and contact management with questions.</p></div>`; let old=$('content').innerHTML; $('content').innerHTML=html; window.print(); $('content').innerHTML=old;}
function exportData(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='condo-maintenance-backup.json';a.click();}
function importData(e){let f=e.target.files[0]; if(!f)return; let r=new FileReader(); r.onload=()=>{db=JSON.parse(r.result);save();init()}; r.readAsText(f);}
init();
